name: testing
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_PAT}}
        
      - name: install
        run: |
          sudo apt update > /dev/null; sudo apt -y install wget python3 python3-pip > /dev/null
          sudo pip install -r req.txt > /dev/null
      - name: start
        run: sudo python3 tes/tes.py
